### ISSUE TITLE
while running [python main_measure.py --measurements  'obj_scn' 'obj_siz'  --dataset 'cityscapes' --folder '\train']

### ISSUE THREAD

**Issue by niponchanda** [princetonvisualai/revise-tool#53]
Traceback (most recent call last):
  File "D:\Bias\Image\Bias_in_image\revise-tool\main_measure.py", line 90, in <module>
    main()
  File "D:\Bias\Image\Bias_in_image\revise-tool\main_measure.py", line 86, in main
    index_to_measurement[meas](dataloader, args)
  File "D:\Bias\Image\Bias_in_image\revise-tool\measurements\object_based.py", line 176, in obj_scn
    group_mapping = dataloader.dataset.group_mapping
  File "C:\Users\nipon.chanda\.conda\envs\bias_env\lib\site-packages\torch\utils\data\dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError

**Comment by Angelina-Wang** [comment]
Thanks for noting this! Just fixed in #54
